// src/config/visual/grass.ts — player-follow GPU grass + flowers

import { GRASS_FOLIAGE_LIGHTING } from './foliage.ts';

export const grass = {
  foliageLighting: GRASS_FOLIAGE_LIGHTING,
  rings: [
    { radius: 20, densityPerM2: 100, bladeWidth: 0.05, segments: 6 },
    { radius: 30, densityPerM2: 25, bladeWidth: 0.075, segments: 1 },
    { radius: 180, densityPerM2: 5, bladeWidth: 0.2, segments: 1 },
  ],
  ringFadeBandM: 16,
  ringFadeBandLod12M: 24,
  ringFadeInLod2M: 12,
  /** Far blades widen by this factor (1× inside widthNearRadius). */
  widthFarGain: 2,
  widthNearRadius: 15,
  widthFarRadius: 45,
  /** Screen-space cull: projected height ≈ fy × bladeHeight / dist. */
  projectedHeightMin: 0.004,
  projectedHeightFull: 0.022,
  stochasticHysteresis: 0.11,
  /** Clump field in data G — strength/coverage/scale/softness re-bake G. */
  clumpStrength: 1,
  clumpScaleM: 7,
  clumpCoverage: 0.5,
  clumpSoftness: 0.25,
  clumpEdgeMinScale: 0.05,
  clumpEdgeDensityBoost: 0.95,
  /** When capped, keep reach and thin density. */
  maxInstancesPerRing: 1_000_000,
  maxBladesPerSide: 2048,
  tileCullEnabled: true,
  tileCullSize: 32,
  bladeHeight: 0.75,
  windStrength: 0.27,
  windSpeed: 0.1,
  bladeMinScale: 0.94,
  bladeMaxScale: 3,
  baseColorDark: '#375C18',
  baseColor: '#678837',
  tipColor: '#53B344',
  rustColor: '#5D3323',
  warmColor: '#C0A850',
  colorMixFactor: 0.25,
  colorVariationStrength: 0.9,
  rustVariationStrength: 0.21,
  warmVariationStrength: 0.48,
  aoRadius: 15,
  aoRimSmoothness: 5,
  aoScale: 0.5,
  sheenStrength: 0.02,
  transmissionStrength: 0.13,
  baseWindShade: 0.75,
  baseShadeHeight: 1,
  baseBending: 3,
  spriteRotationRandomness: 0.05,
  bendDropStrength: 1.3,
  bendControlPoint: 0.4,
  windUvScale: 1.35,
  ambientSwayStrength: 0.055,
  windLull: 0.09,
  windEddyStrength: 0.9,
  windGustCoverage: 0.6,
  windCurveP1: 0.003,
  windCurveP2: 0.85,
  biomeGrassThreshold: 0.05,
  biomeGrassFadeWidth: 0.12,
  transitionMinBladeScale: 0.35,
  biomeDensity: {
    meadow: 1.0,
    forest: 0.55,
    hills: 0.75,
    shore: 0,
    mountain: 0.3,
    path: 0,
  },
  trailGrowthRate: 5,
  trailMinScale: 0.15,
  trailRadius: 0.65,
  trailKDown: 50,
  trailBendStrength: 0.8,
  propGrassPadM: 0,
  propGrassEdgeFadeM: 0.12,
  propGrassCullThreshold: 0.3,
  playerGlowMul: 0.35,
  nightColorFloor: 0.06,
  surfaceBias: 0.04,
  flowers: {
    enabled: true,
    flowersPerSide: 64,
    minScale: 0.075,
    maxScale: 0.135,
    boundsRadius: 1.0,
    grassThreshold: 0.25,
    color1: '#051f54',
    color2: '#fc9400',
    colorStrength: 0.275,
    heightOffset: 0.5,
    alphaTest: 0.15,
  },
} as const;
